name: mock_series
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  easy_debounce: ^2.0.1
  flutter:
    sdk: flutter
  flutter_html: ^2.1.5
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.3
  http: ^0.13.3
  injectable: ^1.5.0
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  json_annotation: ^4.1.0
  json_serializable: ^6.3.1
  uuid: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/main_background.png
    - assets/images/show_background.png
    - assets/images/episode_background.png
    - assets/images/favorites_background.png
    - assets/images/placeholder.png
    - assets/images/transparent_picture.png
