name: mock_series
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  get: ^4.3.8
  get_it: ^7.2.0
  http: ^0.13.3
  injectable: ^1.5.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  injectable_generator: ^1.5.2
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
